- project:
    templates:
      # this job runs py36 and py38, they are the versions used in bionic and
      # focal respectively.
      - openstack-python3-victoria-jobs
      - openstack-cover-jobs
