#!/bin/bash -eux
# Install amulet packages
sudo apt-get update --yes

# Install any additional python packages or software here.
sudo apt-get install --yes python-amulet python-keystoneclient || true
