#!/bin/bash

set -ex

sudo add-apt-repository --yes ppa:juju/stable
sudo apt-get update --yes
sudo apt-get install --yes amulet \
                           distro-info-data \
                           python-cinderclient \
                           python-distro-info \
                           python-glanceclient \
                           python-heatclient \
                           python-keystoneclient \
                           python-neutronclient \
                           python-novaclient \
                           python-pika \
                           python-swiftclient
