#!/usr/bin/python

"""Amulet tests on a basic hacluster deployment on trusty-icehouse."""

from basic_deployment import HAClusterBasicDeployment

if __name__ == '__main__':
    deployment = HAClusterBasicDeployment(series='trusty')
    deployment.run_tests()
