#!/usr/bin/python

"""Amulet tests on a basic hacluster deployment on trusty-juno."""

from basic_deployment import HAClusterBasicDeployment

if __name__ == '__main__':
    deployment = HAClusterBasicDeployment(series='trusty',
                                          openstack='cloud:trusty-juno',
                                          source='cloud:trusty-updates/juno')
    deployment.run_tests()
