#!/usr/bin/python

"""Amulet tests on a basic hacluster deployment on trusty-kilo."""

from basic_deployment import HAClusterBasicDeployment

if __name__ == '__main__':
    deployment = HAClusterBasicDeployment(series='trusty',
                                          openstack='cloud:trusty-kilo',
                                          source='cloud:trusty-updates/kilo')
    deployment.run_tests()
