#!/usr/bin/python

"""Amulet tests on a basic hacluster deployment on trusty-liberty."""

from basic_deployment import HAClusterBasicDeployment

if __name__ == '__main__':
    deployment = HAClusterBasicDeployment(series='trusty',
                                         openstack='cloud:trusty-liberty',
                                         source='cloud:trusty-updates/liberty')
    deployment.run_tests()
