#!/usr/bin/python

"""Amulet tests on a basic hacluster deployment on vivid-kilo."""

from basic_deployment import HAClusterBasicDeployment

if __name__ == '__main__':
    deployment = HAClusterBasicDeployment(series='vivid')
    deployment.run_tests()
