#!/usr/bin/python

"""Amulet tests on a basic hacluster deployment on trusty-mitaka."""

from basic_deployment import HAClusterBasicDeployment

if __name__ == '__main__':
    deployment = HAClusterBasicDeployment(series='trusty',
                                         openstack='cloud:trusty-mitaka',
                                         source='cloud:trusty-updates/mitaka')
    deployment.run_tests()
