#!/usr/bin/env python
#
# Copyright 2016 Canonical Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Amulet tests on a basic hacluster deployment on bionic-rocky."""

from basic_deployment import HAClusterBasicDeployment

if __name__ == '__main__':
    deployment = HAClusterBasicDeployment(series='bionic',
                                          openstack='cloud:bionic-rocky',
                                          source='cloud:bionic-updates/rocky')
    deployment.run_tests()
